import { createHash } from 'node:crypto';
import { atLondon, londonDate, MINUTE_MS as MIN } from './time.mjs';
import { fatigueAt } from './abilities.mjs';
import { surfaceLine } from './downtime.mjs';

// Bounded authored choices, not thoughts generated by a model. Canon anchors:
// manuscript physical pp.64 (gaming), 68 (piano/shared downtime), 161 (Ashai
// wants to be useful), 170 (practice). The short offers and weights below are
// sandbox staging. They grant neither authority nor abilities to either actor.
export const INTENT_EVENT_TYPES = Object.freeze(['INTENT_OFFER', 'INTENT_RESPONSE',
  'INTENT_RENEGOTIATE', 'INTENT_START', 'INTENT_COMPLETE', 'INTENT_INTERRUPTED']);
export const INTENT_FACT_KINDS = Object.freeze(['intent_offer', 'intent_response', 'intent_result']);
export const MOTIVE_WEIGHTS = Object.freeze({
  goaden: Object.freeze({ duty: 10, rest: 8, loyalty: 4, ambition: 3 }),
  ashai: Object.freeze({ autonomy: 5, companionship: 4, rest: 8 }),
});
const TYPES = new Set(INTENT_EVENT_TYPES);
const ACTIVE = new Set(['offered', 'renegotiating', 'reserved', 'started']);
const DURATION = 12 * MIN;
const labels = { game: 'gaming', practice: 'training', quiet: 'quiet_break' };
const rooms = { game: 'gaming_room', practice: 'indoor_yard', quiet: 'common_room' };
const activityText = { game: 'a short game', practice: 'a short practice session', quiet: 'a quiet break' };
const name = who => who === 'goaden' ? 'Goaden' : 'Ashai';
const hash = key => createHash('sha256').update(key).digest().readUInt32BE(0);
const intentOf = state => state.intent ?? initialIntent();
const awakeAtMI6 = actor => actor?.location === 'mi6' && !actor.journey && actor.activity !== 'sleeping';
const together = state => ['goaden', 'ashai'].every(who => awakeAtMI6(state.characters[who]))
  && state.characters.goaden.area === state.characters.ashai.area;
const free = actor => awakeAtMI6(actor) && ['unhurried_time', 'waiting', 'quiet_break'].includes(actor.activity);
const memory = (state, who, key, now) => state.characters[who].knowledge.find(item => item.factKey === key
  && item.learnedAt <= now && (item.validUntil == null || item.validUntil > now));
const tired = (actor, now) => actor.conditions.some(item => ['ordinary_fatigue', 'shaken'].includes(item.kind)
  && item.since <= now && (item.until == null || item.until > now));
const window = now => now >= atLondon(londonDate(now), '18:40') && now <= atLondon(londonDate(now), '19:05');
const currentMemories = (state, who, now, kinds) => state.characters[who].knowledge.filter(item =>
  memory(state, who, item.factKey, now) && kinds.includes(state.facts[item.factKey]?.kind));

export function initialIntent() { return { opportunities: {}, instances: {} }; }

export function competingCommitments(state, who, startAt, endAt, ownKey = null) {
  return Object.entries(state.arrangements).filter(([key, item]) => key !== ownKey
    && ['accepted', 'started'].includes(item.status) && item.party.includes(who)
    && item.startAt < endAt && item.until > startAt).map(([key, item]) => ({ key, ...item }));
}

export function chooseIntentMotive(state, now, seed, key, startAt, endAt, ownKey = null) {
  const goaden = state.characters.goaden;
  const competing = competingCommitments(state, 'goaden', startAt, endAt, ownKey);
  const duty = currentMemories(state, 'goaden', now, ['duty_callout']);
  if (['on_call', 'in_a_briefing'].includes(goaden.activity) || competing.length || duty.length)
    return { motive: 'duty', factKeys: duty.map(item => item.factKey),
      eventIds: competing.flatMap(item => [item.sourceEventId, item.acceptanceEventId]).filter(Boolean),
      reason: competing.length ? 'existing_commitment' : 'current_duty' };
  if (tired(goaden, now) || fatigueAt(state, 'goaden', now) >= 3) return { motive: 'rest', factKeys: [],
    eventIds: goaden.conditions.filter(item => ['ordinary_fatigue', 'shaken'].includes(item.kind))
      .map(item => item.sourceEventId).concat(state.abilities?.actors?.goaden?.track?.sourceEventId
        ?? state.abilities?.actors?.goaden?.fatigueEventId).filter(Boolean), reason: 'current_condition' };
  const recent = currentMemories(state, 'goaden', now, ['broken_plan', 'intent_result'])
    .filter(item => now - item.learnedAt <= 7 * 24 * 60 * MIN)
    .sort((first, second) => second.learnedAt - first.learnedAt || first.factKey.localeCompare(second.factKey));
  const repair = recent.find(item => state.facts[item.factKey].kind === 'broken_plan'
    || ['interrupted', 'declined'].includes(item.value.outcome));
  if (repair) return { motive: 'loyalty', factKeys: [repair.factKey], eventIds: [], reason: 'remembered_unkept_time' };
  const last = recent.find(item => item.value.outcome === 'completed' && now - item.learnedAt <= 2 * 24 * 60 * MIN);
  if (last) return { motive: last.value.activity === 'game' ? 'ambition' : 'loyalty',
    factKeys: [last.factKey], eventIds: [], reason: 'recent_shared_activity' };
  return { motive: hash(`${seed}|intent-v1|${key}/motive`) % 7 < 4 ? 'loyalty' : 'ambition',
    factKeys: [], eventIds: [], reason: 'ordinary_preference' };
}

export function intentEncounterActions({ state, day, now, parentActionId, parentEventId, seed }) {
  if (!parentActionId || !parentEventId || intentOf(state).opportunities[day] || !window(now) || !window(now + MIN)
    || !together(state) || !free(state.characters.ashai)
    || Object.values(intentOf(state).instances).some(item => ACTIVE.has(item.status))
    || hash(`${seed}|intent-v1|${day}/opportunity`) % 3 !== 0) return [];
  return [{ id: `${parentActionId}/intent/offer`, type: 'INTENT_OFFER', dueAt: now + MIN,
    priority: 27, day, actors: ['ashai', 'goaden'], version: 1,
    originActionId: parentActionId, originEventId: parentEventId }];
}

const shape = a => ({ type: a.type, dueAt: a.dueAt, day: a.day, version: a.version,
  priority: a.priority, actors: a.actors ?? [], actor: a.actor ?? null,
  originActionId: a.originActionId ?? null, originEventId: a.originEventId ?? null });
const matches = (a, owned) => owned && JSON.stringify(shape(a)) === JSON.stringify(owned.shape);
function save(ctx, item) {
  ctx.ops.setIntent({ ...intentOf(ctx.state), instances: { ...intentOf(ctx.state).instances, [item.id]: item } });
}
export function issueIntentActions(ctx, actions) {
  const issued = [];
  for (const a of actions) {
    if (!TYPES.has(a.type) || a.version !== 1 || !Number.isFinite(a.dueAt) || a.dueAt <= ctx.now)
      throw new Error('Intent actions must follow their recorded cause');
    const owned = { shape: shape(a), sourceEventId: ctx.id, consumed: false };
    if (a.type === 'INTENT_OFFER') {
      if (intentOf(ctx.state).opportunities[a.day]) continue;
      ctx.ops.setIntent({ ...intentOf(ctx.state), opportunities: {
        ...intentOf(ctx.state).opportunities, [a.day]: { ...owned, actionId: a.id } } });
    } else {
      const item = intentOf(ctx.state).instances[a.intentId];
      if (!item || item.token !== a.intentToken || item.actions[a.id]) continue;
      if (Object.keys(item.actions).length >= 6) throw new Error('Intent action budget exceeded');
      save(ctx, { ...item, actions: { ...item.actions, [a.id]: owned } });
    }
    issued.push(a);
  }
  return issued;
}
function follow(ctx, item, type, slug, dueAt) {
  ctx.followups.push(...issueIntentActions(ctx, [{ id: `${ctx.action.id}/${slug}`, type,
    dueAt, priority: 27, day: londonDate(dueAt), actors: ['goaden', 'ashai'], version: 1,
    intentId: item.id, intentToken: item.token }]));
}
function evidence(ctx, decision) {
  for (const key of decision.factKeys) ctx.ops.useMemory('goaden', key);
  ctx.event.causedBy.push(...decision.eventIds);
}
function scene(kind) {
  const a = text => ({ who: 'ashai', expression: 'thoughtful', text });
  const g = text => ({ who: 'goaden', expression: 'idle', text });
  return {
    accepted: [a('Twelve minutes. Something we actually finish.'), g('You timed it?'),
      a('I know who I am asking.'), g('All right. Twelve minutes.')],
    practice: [g('Short practice instead? Nothing elaborate.'), a('You can ask. I can also say no.'),
      g('I am asking.'), a('Twelve minutes, then. Keep it ordinary.')],
    quiet: [g('Could we make it quiet? Just for a bit.'), a('No competition?'),
      g('Not even a little one.'), a('That I can arrange.')],
    declined: [g('I have already committed that time.'), a('Then say that first.'),
      g('I am saying it now.'), a('All right. This one can wait.')],
  }[kind].map(line => ({ ...line }));
}
function publicLine(ctx, item, text, variant = null) {
  ctx.event.location = 'mi6'; ctx.event.area = ctx.state.characters.ashai.area;
  ctx.event.participants = together(ctx.state) ? ['goaden', 'ashai'] : [];
  ctx.event.payload = { intentId: item.id, status: item.status, activity: item.selected ?? item.proposed,
    ...(variant && together(ctx.state) ? { venue: 'mi6', mood: 'ordinary_negotiation', cast: ['goaden', 'ashai'], lines: scene(variant) } : {}) };
  ctx.ops.publish(text);
}
function result(ctx, item, outcome, text) {
  const factKey = `${item.id}:result`;
  const fact = ctx.ops.createFact(factKey, 'intent_result', 'both', { intentId: item.id,
    outcome, activity: item.selected ?? item.proposed, presentationText: text }, null);
  const witnesses = together(ctx.state) ? item.party : outcome === 'interrupted'
    ? item.party.filter(who => who === item.interruptionActor
      || item.startEventId && ctx.state.characters[who].activityId === item.startEventId) : [];
  for (const who of witnesses) ctx.ops.learn(who, fact, 'participated');
  const final = { ...item, status: outcome, completedAt: ctx.now, resultEventId: ctx.id, resultFactKey: factKey };
  save(ctx, final);
  return final;
}
function reserve(ctx, item, activity) {
  const arrangement = ctx.state.arrangements[item.arrangementKey];
  const reserved = { ...item, status: 'reserved', selected: activity, acceptanceEventId: ctx.id };
  save(ctx, reserved);
  ctx.ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'accepted', activity,
    acceptedAt: ctx.now, acceptanceEventId: ctx.id, public: true });
  for (const who of item.party) ctx.ops.setActor(who, 'publicNext', {
    at: item.startAt, description: `An agreed ${activityText[activity].replace(/^a /, '')} at MI6`, intentId: item.id });
  follow(ctx, reserved, 'INTENT_START', 'start', item.startAt);
  return reserved;
}

// Call before replacing activity or beginning travel. This never changes the
// incoming routine: only the old promise is broken. Its owned release later
// clears the other participant if they are still doing this session.
export function interruptIntent(ctx, actorId, reason = 'activity_replaced') {
  const actor = ctx.state.characters[actorId];
  const item = Object.values(intentOf(ctx.state).instances).find(entry => entry.party.includes(actorId)
    && (entry.status === 'started' && actor.activityId === entry.startEventId
      || entry.status === 'reserved' && /TRAVEL|DUTY|CALL|BRIEF|INCIDENT|PLAN_BROKEN/.test(reason)));
  if (!item) return null;
  const interrupted = { ...item, status: 'interrupting', interruptedAt: ctx.now,
    interruptionEventId: ctx.id, interruptionReason: reason, interruptionActor: actorId };
  save(ctx, interrupted);
  const r = ctx.state.arrangements[item.arrangementKey];
  ctx.ops.setArrangement(item.arrangementKey, { ...r, status: 'broken', brokenEventId: ctx.id });
  ctx.event.causedBy.push(item.acceptanceEventId, item.startEventId ?? item.originEventId);
  follow(ctx, interrupted, 'INTENT_INTERRUPTED', 'intent-interrupted', ctx.now + 1);
  return interrupted;
}

export function resolveIntentAction(ctx) {
  const { state, action: a, now, id, ops } = ctx;
  if (!TYPES.has(a.type)) return false;
  const refuse = reason => { ops.skip(reason); return true; };
  if (a.type === 'INTENT_OFFER') {
    const owned = intentOf(state).opportunities[a.day];
    if (!owned || owned.consumed || owned.actionId !== a.id || !matches(a, owned)
      || a.originEventId !== owned.sourceEventId || a.version !== 1) return refuse('No owned intention opportunity');
    ops.setIntent({ ...intentOf(state), opportunities: { ...intentOf(state).opportunities,
      [a.day]: { ...owned, consumed: true } } });
    if (!together(state) || !free(state.characters.ashai) || !window(now)
      || Object.values(intentOf(state).instances).some(item => ACTIVE.has(item.status)))
      return refuse('No available evening encounter for an offer');
    const proposed = tired(state.characters.ashai, now) ? 'quiet' : 'game';
    const intentId = `intent:${createHash('sha256').update(`${id}|v1`).digest('hex').slice(0, 24)}`;
    const item = { id: intentId, version: 1, token: `${id}:intent-v1`, day: a.day,
      party: ['goaden', 'ashai'], requester: 'ashai', originEventId: id, originActionId: a.id,
      status: 'offered', proposed, selected: null, openedAt: now, startAt: now + 3 * MIN,
      endAt: now + 3 * MIN + DURATION, arrangementKey: `${intentId}:arrangement`, actions: {},
      offerFactKey: `${intentId}:offer`, responseFactKey: null, privateDecision: null,
      acceptanceEventId: null, startEventId: null, completedAt: null, resultEventId: null, resultFactKey: null };
    save(ctx, item);
    ops.setArrangement(item.arrangementKey, { party: [...item.party], requester: 'ashai', activity: proposed,
      startAt: item.startAt, until: item.endAt, duration: 12, status: 'offered', public: true,
      sourceEventId: id, textKey: proposed, intentId, knowledgeSource: null });
    // 'with twelve minutes set aside' is a duration, not a sentence. What a
    // reader needs is who asked, for what, and how long they have got.
    const inHall = ctx.state.characters.ashai.area === 'common_room';
    const OFFER = { game: [
        `Ashai asked Goaden for twelve minutes on the game${inHall ? ' in the lunch hall' : ''}.`,
        `Twelve minutes on the game, Ashai said${inHall ? ', across the lunch hall table' : ''}. Goaden heard her out.`,
        `Ashai wanted twelve minutes of the game and asked Goaden for them.`,
        `Ashai put the game to Goaden. Twelve minutes, she said, and meant it.`,
        `Ashai asked for the game${inHall ? ' before the lunch hall had properly cleared' : ''}. Twelve minutes; she was firm about the number.`,
      ], practice: [
        'Ashai asked Goaden down to the yard for twelve minutes of practice.',
        'Twelve minutes of practice, Ashai said. Goaden looked at the clock before he looked at her.',
        'Ashai wanted twelve minutes on the yard and asked Goaden to give them.',
        'Ashai put twelve minutes of practice to Goaden, which was the number that usually got a yes.',
      ], quiet: [
        'Ashai asked Goaden for twelve minutes of nothing in particular.',
        'Twelve minutes of nothing, Ashai said. Goaden did not need persuading.',
        'Ashai asked for twelve quiet minutes, and did not say what for.',
        'Ashai wanted twelve minutes with nothing in them and asked Goaden to share them.',
      ] };
    const text = OFFER[proposed] ? surfaceLine(id, OFFER[proposed]) : `Ashai proposed ${activityText[proposed]} together at MI6.`;
    const fact = ops.createFact(item.offerFactKey, 'intent_offer', 'both',
      { intentId, activity: proposed, startAt: item.startAt, endAt: item.endAt, presentationText: text }, item.endAt + 1);
    for (const who of item.party) ops.learn(who, fact, 'participated');
    ctx.event.causedBy.push(a.originEventId); publicLine(ctx, item, text);
    follow(ctx, item, 'INTENT_RESPONSE', 'response', now + MIN);
    return true;
  }
  let item = intentOf(state).instances[a.intentId];
  const owned = item?.actions[a.id];
  if (!item || item.version !== 1 || a.version !== 1 || item.token !== a.intentToken
    || !matches(a, owned) || owned.consumed) return refuse('No owned intention action');
  if (!ACTIVE.has(item.status) && !(a.type === 'INTENT_INTERRUPTED' && item.status === 'interrupting'))
    return refuse('This intention has already ended');
  item = { ...item, actions: { ...item.actions, [a.id]: { ...owned, consumed: true } } };
  save(ctx, item); ctx.event.causedBy.push(owned.sourceEventId, item.originEventId);
  const arrangement = state.arrangements[item.arrangementKey];
  if (a.type === 'INTENT_RESPONSE' || a.type === 'INTENT_RENEGOTIATE') {
    if (!together(state) || !['goaden', 'ashai'].every(who => ops.useMemory(who, item.offerFactKey))) {
      ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'deferred' });
      item = result(ctx, item, 'declined', 'The short MI6 offer lapsed before they could agree it.');
      publicLine(ctx, item, 'The short MI6 offer lapsed before Goaden and Ashai could agree it.');
      return true;
    }
    if (a.type === 'INTENT_RESPONSE') {
      if (item.status !== 'offered') return refuse('No unanswered offer');
      const decision = chooseIntentMotive(state, now, ctx.seed, item.id, item.startAt, item.endAt, item.arrangementKey);
      evidence(ctx, decision);
      item = { ...item, privateDecision: decision };
      const selected = decision.motive === 'rest' ? 'quiet' : decision.motive === 'ambition' ? 'practice' : item.proposed;
      const responseText = decision.motive === 'duty' ? 'Goaden declined the short shared session because he was already committed.'
        : selected === item.proposed ? `Goaden accepted Ashai’s offer of ${activityText[selected]}.`
          : `Goaden suggested ${activityText[selected]} instead of the original plan.`;
      const responseFactKey = `${item.id}:response`;
      const fact = ops.createFact(responseFactKey, 'intent_response', 'both',
        { intentId: item.id, response: decision.motive === 'duty' ? 'declined' : selected === item.proposed ? 'accepted' : 'counteroffer',
          activity: selected, presentationText: responseText }, null);
      for (const who of item.party) ops.learn(who, fact, 'participated');
      item = { ...item, responseFactKey };
      save(ctx, item);
      if (decision.motive === 'duty') {
        ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'deferred' });
        item = result(ctx, item, 'declined', responseText);
        publicLine(ctx, item, responseText, 'declined');
      } else if (selected === item.proposed) {
        item = reserve(ctx, item, selected); publicLine(ctx, item, responseText, 'accepted');
      } else {
        item = { ...item, status: 'renegotiating', selected }; save(ctx, item);
        publicLine(ctx, item, responseText);
        follow(ctx, item, 'INTENT_RENEGOTIATE', 'renegotiate', now + MIN);
      }
    } else {
      if (item.status !== 'renegotiating' || !['goaden', 'ashai'].every(who => ops.useMemory(who, item.responseFactKey)))
        return refuse('No shared counteroffer to consider');
      const conflict = competingCommitments(state, 'ashai', item.startAt, item.endAt, item.arrangementKey).length;
      if (conflict || item.selected === 'practice' && (tired(state.characters.ashai, now) || fatigueAt(state, 'ashai', now) >= 3)) {
        ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'deferred' });
        item = result(ctx, item, 'declined', 'Ashai declined the revised session. They left that time unreserved.');
        publicLine(ctx, item, 'Ashai declined the revised session. They left that time unreserved.');
      } else {
        item = reserve(ctx, item, item.selected);
        publicLine(ctx, item, `Ashai agreed to ${activityText[item.selected]} instead. The twelve-minute limit stayed.`, item.selected);
      }
    }
  } else if (a.type === 'INTENT_START') {
    if (item.status !== 'reserved' || arrangement.status !== 'accepted' || now !== item.startAt)
      return refuse('No matching reserved session');
    if (!together(state) || !item.party.every(who => free(state.characters[who]))
      || item.party.some(who => competingCommitments(state, who, item.startAt, item.endAt, item.arrangementKey).length)) {
      // A reserved session can fail without replacing either actor's new duty.
      item = { ...item, status: 'interrupting', interruptionEventId: id, interruptedAt: now,
        interruptionReason: 'reserved_start_unavailable' }; save(ctx, item);
      ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'broken', brokenEventId: id });
      follow(ctx, item, 'INTENT_INTERRUPTED', 'interrupted', now + 1);
      return refuse('The reserved start was no longer available');
    }
    item = { ...item, status: 'started', startEventId: id }; save(ctx, item);
    ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'started', startedEventId: id });
    for (const who of item.party) {
      ops.useMemory(who, item.responseFactKey);
      ops.activity(who, labels[item.selected], null, rooms[item.selected]);
      ops.setActor(who, 'activityUntil', item.endAt);
      if (state.characters[who].publicNext?.intentId === item.id) ops.setActor(who, 'publicNext', null);
    }
    const began = activityText[item.selected].replace(/^a /, '');
    publicLine(ctx, item, surfaceLine(id, [
      `Goaden and Ashai began their agreed ${began}.`, `The agreed ${began} began on time, which is not always how it goes.`,
      `Goaden and Ashai started the ${began} they had agreed.`, `The ${began} began. Twelve minutes had been promised for it.`,
      `Goaden and Ashai got to their ${began} more or less when they said they would.`,
    ]));
    follow(ctx, item, 'INTENT_COMPLETE', 'complete', item.endAt);
  } else if (a.type === 'INTENT_COMPLETE') {
    if (item.status !== 'started' || now !== item.endAt) return refuse('No matching session to finish');
    if (!item.party.every(who => state.characters[who].activityId === item.startEventId
      && state.characters[who].activity === labels[item.selected] && state.characters[who].activityUntil === item.endAt
      && state.characters[who].location === 'mi6' && state.characters[who].area === rooms[item.selected]
      && !state.characters[who].journey)) {
      item = { ...item, status: 'interrupting', interruptionEventId: id, interruptedAt: now,
        interruptionReason: 'session_ownership_lost' }; save(ctx, item);
      ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'broken', brokenEventId: id });
      follow(ctx, item, 'INTENT_INTERRUPTED', 'interrupted', now + 1);
      return refuse('The agreed session did not retain its participants');
    }
    item = result(ctx, item, 'completed', `Goaden and Ashai finished the ${activityText[item.selected].replace(/^a /, '')} they had agreed.`);
    ops.setArrangement(item.arrangementKey, { ...arrangement, status: 'completed', completionEventId: id });
    for (const who of item.party) ops.activity(who, 'unhurried_time', null, rooms[item.selected]);
    ctx.event.causedBy.push(item.startEventId, item.acceptanceEventId);
    const done = activityText[item.selected].replace(/^a /, '');
    publicLine(ctx, item, surfaceLine(id, [
      `Goaden and Ashai finished their agreed ${done}. The time had actually been kept.`,
      `The agreed ${done} ended when it was meant to. Neither of them mentioned that this was unusual.`,
      `Goaden and Ashai finished the ${done}, inside the time, for once.`,
      `The ${done} ran its twelve minutes and stopped. Goaden and Ashai kept to it.`,
    ]));
  } else if (a.type === 'INTENT_INTERRUPTED') {
    if (item.status !== 'interrupting' || !item.interruptionEventId) return refuse('No interrupted session to release');
    item = result(ctx, item, 'interrupted', 'The short shared MI6 session was interrupted and remained uncompleted.');
    for (const who of item.party) {
      const actor = state.characters[who];
      if (item.startEventId && actor.activityId === item.startEventId && awakeAtMI6(actor))
        ops.activity(who, 'unhurried_time', null, actor.area);
      if (actor.publicNext?.intentId === item.id) ops.setActor(who, 'publicNext', null);
    }
    ctx.event.causedBy.push(item.interruptionEventId, item.acceptanceEventId ?? item.originEventId);
    publicLine(ctx, item, 'Goaden and Ashai’s short shared session was interrupted. It was not recorded as time kept.');
  }
  return true;
}

export function publicIntentSummaries(state, now) {
  return Object.values(intentOf(state).instances).filter(item => item.openedAt <= now
    && now - (item.completedAt ?? item.openedAt) <= 2 * 24 * 60 * MIN).slice(-3).map(item => ({
    id: item.id, status: item.status, activity: item.selected ?? item.proposed,
    startAt: item.startAt, endAt: item.endAt, eventId: item.resultEventId ?? item.originEventId,
    description: item.status === 'completed' ? `Their agreed ${activityText[item.selected].replace(/^a /, '')} was completed.`
      : item.status === 'declined' ? 'The short shared offer was declined.'
        : ['interrupted', 'interrupting'].includes(item.status) ? 'The short shared session was interrupted.'
          : `Ashai’s offer of ${activityText[item.selected ?? item.proposed]} is ${item.status}.`,
  }));
}

export function assertIntent(state) {
  const intent = state.intent;
  if (!intent || !intent.opportunities || !intent.instances) throw new Error('Invalid intent state');
  if (Object.values(intent.instances).filter(item => ACTIVE.has(item.status) || item.status === 'interrupting').length > 1)
    throw new Error('Overlapping intention reservations');
  const dates = new Set();
  for (const item of Object.values(intent.instances)) {
    if (dates.has(item.day) || item.version !== 1 || item.requester !== 'ashai'
      || item.party.join(',') !== 'goaden,ashai' || !labels[item.proposed]
      || item.selected && !labels[item.selected] || !item.originEventId || !item.token
      || ![...ACTIVE, 'interrupting', 'completed', 'declined', 'interrupted'].includes(item.status)
      || item.endAt - item.startAt !== DURATION || item.startAt <= item.openedAt
      || Object.keys(item.actions).length > 6 || !intent.opportunities[item.day]?.consumed)
      throw new Error('Invalid bounded character intention');
    dates.add(item.day);
    const arrangement = state.arrangements[item.arrangementKey];
    if (!arrangement || arrangement.intentId !== item.id || arrangement.requester !== 'ashai'
      || arrangement.startAt !== item.startAt || arrangement.until !== item.endAt)
      throw new Error('Intention lacks its existing arrangement reservation');
    if (['reserved', 'started', 'completed'].includes(item.status) && !item.acceptanceEventId)
      throw new Error('Unaccepted intention started');
    if (['started', 'completed'].includes(item.status) && !item.startEventId)
      throw new Error('Intention completion lacks actual start');
    if (['completed', 'declined', 'interrupted'].includes(item.status)) {
      const fact = state.facts[item.resultFactKey];
      if (!fact || fact.kind !== 'intent_result' || fact.sourceEventId !== item.resultEventId
        || fact.value.intentId !== item.id || fact.value.outcome !== item.status)
        throw new Error('Intention ending lacks event-linked memory');
    }
  }
}
